export enum Symbols {
  // temporal placeholder until full symexec is implemented
  UNKNOWN = 'UNKNOWN',
  EMPTY = 'EMPTY',

  CALL = 'CALL',
  STATICCALL = 'STATICCALL',
  CALLCODE = 'CALLCODE',
  DELEGATECALL = 'DELEGATECALL',
  RETURNDATASIZE = 'RETURNDATASIZE',
  RETURNDATACOPY = 'RETURNDATACOPY',

  ADDRESS = 'ADDRESS',
  ORIGIN = 'ORIGIN',
  CALLER = 'CALLER',
  BALANCE = 'BALANCE',
  CALLVALUE = 'CALLVALUE',
  CALLDATASIZE = 'CALLDATASIZE',
  CALLDATALOAD = 'CALLDATALOAD',
  CODESIZE = 'CODESIZE',
  GAS = 'GAS',
  BLOCKHASH = 'BLOCKHASH',
  COINBASE = 'COINBASE',
  TIMESTAMP = 'TIMESTAMP',
  NUMBER = 'NUMBER',
  DIFFICULTY = 'DIFFICULTY',
  GASLIMIT = 'GASLIMIT',
  GASPRICE = 'GASPRICE',
  EXTCODESIZE = 'EXTCODESIZE',
  CREATE = 'CREATE'
}
